### ISSUE TITLE
Quantity comparisons

### ISSUE THREAD

**Issue by RJaBi** [ILAFF/ILAFF#15] opened 2020-06-30 04:50 UTC
Equality conditions on Quantity's don't work for numpy arrays of quantities.

Minimal working example to reproduce is below

```
from ilaff import units
import numpy as np
#A single. This works                                                                                                  
b = 1 * units.fm
if b == b:
    print('Singleton works')
#A numpy single. This works                                                                                            
b = np.arange(0,1) * units.fm    #i.e. np.array([0])*units.fm                                                          
if b == b:
    print('Numpy singleton works')
#A list of quantities. This works                                                                                                                                                                                  
b = [1*units.fm]*2
if b == b:
    print('List of quantities works')
#A nump array. This doesn't work                                                                                       
b = np.arange(0,2) * units.fm    #i.e. np.array([0,1])*units.fm                                                        
if b == b:
    print('Numpy array doesnt work')
#Error is                                                                                                              
#ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()               
```
I believe the desired/expected behaviour is all(). This is a simple change on the face of it, change i.e.
`return self.value == other.value` however this breaks the first case considered. Looking around, the two solutions to test if something is an iterable (and hence eligible for all() ) are
```
def iterable(obj):
    try:
        iter(obj)
    except Exception:
        return False
    else:
        return True
```
Or
```
from collections.abc import Iterable   # drop `.abc` with Python 2.7 or lower
def iterable(obj):
    return isinstance(obj, Iterable)
```
where apparently the first is preferred. Does anyone else have thoughts about this? Or is this something that iterably will fix @FinnStokes ?

**Comment by FinnStokes** [comment] 2020-06-30 09:00
I'm happy to change this, but this is actually working as intended. I've been trying to make a quantity wrapping a numpy array behave as much like a numpy array as possible. When you compare two numpy arrays, you get a numpy array of booleans back. Once #16 is resolved, this should allow us to use numpy's array masking, like:
```python
from ilaff import units
import numpy as np
t = np.arange(1,10) * units.fm
m = 1 / t
m[t > 3] # gives [0.04933174 0.0394654 0.03288783 0.02818957 0.02466587 0.02192522] GeV
```

Because the comparison operators on numpy return raw numpy arrays, you can call `all` on the result like you would any numpy comparison. We could change our methods to apply that before returning, but that would be a divergence from the numpy interface.

**Comment by FinnStokes** [comment] 2020-07-01 14:13
After discussing this in the meeting, I'm going to say this is working as intended and close the issue. If someone feels strongly about it, we can revisit at a later date.

**Closed as completed by FinnStokes** 2020-07-01 14:13 UTC
Labels: bug, wontfix
